name: Clang Format

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - '.github/workflows/clang-format.yml'
  pull_request:
    paths:
      - 'clang/**'

jobs:
  build_clang:
    name: clang-format
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@master
      with:
        arch: amd64
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build clang-format
      uses: llvm/actions/build-test-llvm-project@master
      with:
        cmake_args: -G Ninja  -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-static-libgcc" -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
        build_target: clang-format
